on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32rom Unstable

jobs:
  fox32rom-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download latest fox32asm version
        uses: robinraju/release-downloader@v1
        with:
          repository: 'fox32-arch/fox32asm'
          latest: true
          extract: true
          fileName: '*-x86_64-linux.zip'

      - name: Install lua5.4, vim
        run: |
          sudo apt update
          sudo apt install -y lua5.4 vim

      - name: Build
        run: |
          chmod +x ./fox32asm
          make FOX32ASM=./fox32asm

      - name: Upload fox32.rom
        uses: actions/upload-artifact@v4
        with:
          name: fox32.rom
          path: fox32.rom

      - name: Upload fox32rom.h
        uses: actions/upload-artifact@v4
        with:
          name: fox32rom.h
          path: fox32rom.h

      - name: Upload fox32rom.def
        uses: actions/upload-artifact@v4
        with:
          name: fox32rom.def
          path: fox32rom.def
