on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32rom Unstable

jobs:
  fox32rom-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download latest fox32asm artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/fox32asm
          workflow: fox32asm-unstable-linux.yml
          workflow_conclusion: success

      - name: Install lua5.4
        run: |
          sudo apt update
          sudo apt install -y lua5.4

      - name: Build
        run: |
          chmod +x fox32asm/fox32asm
          make FOX32ASM=fox32asm/fox32asm

      - name: Upload fox32.rom
        uses: actions/upload-artifact@v2
        with:
          name: fox32.rom
          path: fox32.rom

      - name: Upload fox32rom.def
        uses: actions/upload-artifact@v2
        with:
          name: fox32rom.def
          path: fox32rom.def
